name: Cron Reminders
on:
  schedule:
    - cron: '*/10 * * * *'  # every 10 minutes
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping reminders endpoint
        run: |
          curl -X POST "$API_URL/jobs/run-due-reminders?cron_key=$CRON_KEY"
        env:
          API_URL: ${{ secrets.API_URL }}
          CRON_KEY: ${{ secrets.CRON_KEY }}
